version: 2.1

defaults: &defaults
  working_directory: ~/feathery-react
  docker:
    - image: cimg/node:14.17

jobs:
  # Checkout the repository
  # Pull node_modules from the CircleCI cache or install directly
  # Persist all the files for later use
  setup:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - package-dependencies-v2-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: package-dependencies-v2-{{ checksum "yarn.lock" }}
      - persist_to_workspace:
          root: ~/feathery-react
          paths: .

  # Execute unit tests
  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run: yarn lint
      - run: yarn test

  # Build the Node-ready package
  build-node:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run: yarn build:node

  # Build the <script />-ready package
  build-umd:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run: yarn build:umd

workflows:
  version: 2.1
  pipeline:
    jobs:
      - setup
      - test:
          requires:
            - setup
      - build-node:
          requires:
            - setup
      - build-umd:
          requires:
            - setup
